apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:e437595b20887da02d37949296f9300935b40a94eadd31860c1a751945d024e7
  name: quay.io/adhis/argo-05
  newName: quay.io/adhis/argo-05
