apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:a6a3bd7fae2c746169c5f5e98cd4944c3bb6d3569f3b76f53c32b23f80b4726b
  name: quay.io/adhis/java
  newName: quay.io/adhis/java
