apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:978250d0a58cf06505a8dcc70f413363c5d438f16df999aa2169dc6d1a620aa4
  name: quay.io/sumitbiswal/jenkins-agent-maven
  newName: quay.io/sumitbiswal/jenkins-agent-maven
